language: bash
install: |
  wget 'http://ftp.debian.org/debian/pool/main/s/shellcheck/shellcheck_0.4.4-4_amd64.deb' && \
  sudo dpkg -i shellcheck_*.deb
script:
  - shellcheck -s bash -e SC1083 jetbrains-backup.sh || exit 1;
  - shellcheck -s bash -e SC1083 jetbrains-uninstall.sh || exit 1;
